// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


let { graphql } = require("gatsby")
;

var query = (graphql`
  fragment ImageFluidB on ImageSharpFluid   {
    srcSet
    src
    sizes
    aspectRatio
  }
`);

var Raw = { };

function parse(value) {
  return {
          srcSet: value.srcSet,
          src: value.src,
          sizes: value.sizes,
          aspectRatio: value.aspectRatio
        };
}

var verifyArgsAndParse = parse;

function serialize(value) {
  var value$1 = value.aspectRatio;
  var value$2 = value.sizes;
  var value$3 = value.src;
  var value$4 = value.srcSet;
  return {
          srcSet: value$4,
          src: value$3,
          sizes: value$2,
          aspectRatio: value$1
        };
}

var Z__INTERNAL = {
  graphql: 0,
  graphql_module: 0
};

var name = "ImageFluidB";

export {
  query ,
  Raw ,
  parse ,
  verifyArgsAndParse ,
  serialize ,
  name ,
  Z__INTERNAL ,
  
}
/*  Not a pure module */
