// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Raw = {};

var query = (graphql`
  fragment ImageFluidB on ImageSharpFluid   {
    srcSet
    src
    sizes
    aspectRatio
  }
`);

function parse(value) {
  return {
          srcSet: value.srcSet,
          src: value.src,
          sizes: value.sizes,
          aspectRatio: value.aspectRatio
        };
}

function verifyArgsAndParse(_ImageFluidB, value) {
  return parse(value);
}

function serialize(value) {
  var value$1 = value.aspectRatio;
  var value$2 = value.sizes;
  var value$3 = value.src;
  var value$4 = value.srcSet;
  return {
          srcSet: value$4,
          src: value$3,
          sizes: value$2,
          aspectRatio: value$1
        };
}

function verifyName(param) {
  
}

var Z__INTERNAL = {
  graphql: 0,
  graphql_module: 0
};

export {
  Raw ,
  query ,
  parse ,
  verifyArgsAndParse ,
  serialize ,
  verifyName ,
  Z__INTERNAL ,
  
}
/* query Not a pure module */
